repository_type: pipeline

nf_core_version: 3.5.1

lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config

template:
  org: nf-core
  name: training
  description: nf-core training
  author: Fernando Duarte
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - fastqc
    - gpu
  is_nfcore: true
